apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: rag
spec:
  selector:
    matchLabels:
      app: qdrant
  serviceName: qdrant-service
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
          env:
            - name: QDRANT__SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: QDRANT_API_KEY
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6333
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6333
            initialDelaySeconds: 30
            periodSeconds: 10
      
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc